staff/urls.py
from django.urls import path
from .views import (
    StaffListView,
    EmployeeDetailView,
    UserDetailView,
    UserListView,
    index,
)

app_name = "staff"  # имя приложения, которое будет использоваться в шаблонах

urlpatterns = [
    # для FBV представления
    # path('', index),                  # для FBV представления ссылка на функцю-обработчик staff/views/index.py
    # path('employee/<int:pk>/', detail),   # для FBV представления ссылка на функцю-обработчик staff/views/detail.py,
    # /<int:pk>/ - параметр пути в url для передачи в функцию-обработчик staff/views/detail.py
    # int - это конвертер типа пути, который преобразует строку в неотрицательное целое число
    
    # для CBV представления
    # используются классы EmployeeListView EmployeeDetailView в staff/views.py,
    # а в name= указывается 'user-list' 'user-detail' 'staff-list' 'employee-detail'- имена url-паттернов (в шаблонах),
    # /<int:pk>/ - параметр пути в url для встроенной функции-обработчик в классе DetailView
    # с конвертером int (строку в неотрицательное целое).
    # При необходимости изменения адреса страницы достаточно изменить адрес только в   path(''...   - имена url не меняются.

    path(
        "employee/<int:pk>/",
        EmployeeDetailView.as_view(),
        name="employee-detail",
    ),  # URL страницы с карточкой сотрудника
    path(
        "user/<int:pk>/",
        UserDetailView.as_view(),
        name="user-detail",
    ),  # URL страницы с карточкой пользователя
    path(
        "staff/",
            StaffListView.as_view(),
        name="staff-list-all",
    ),  # URL страницы со списком всех сотрудников
    path(
        "",
        #UserListView.as_view(),
        #name="user-list",
        StaffListView.as_view(),
        name="staff-last4",
    ),  # URL главной страницы со списком 4х недавно принятых сотрудников
]
   

staffmanager/urls.py
from django.contrib import admin
from django.urls import include, path

# импортируем модуль views из папки staff, содержащую функции-обработчики запросов
from staff import views

# импорт модуля debug_toolbar
import debug_toolbar

# Импорт редактора django-ckeditor-5
import django_ckeditor_5

# импорт модуля settings и функции static
# для настройки обработки медиа-файлов проекта в режиме debug
# Кроме этого, в шаблонах следует загружать тег {% load static %}
from django.conf import settings
from django.conf.urls.static import static


# Список всех адресов обработчиков запросов
urlpatterns = [
    # URL для обработчика staffmanager\staff\views.py\index()
    # path("", views.index),
    # Путь поиска ссылок в приложении staff для главной страницы
    path("", include("staff.urls")),
    # URL для обработчика из модуля admin.py
    path("admin/", admin.site.urls, name="admin"),
    # URL для обработчика из проекта DjDt
    path("__debug__/", include(debug_toolbar.urls)),
    # URL для редактора django-ckeditor-5
    path("admin/", include("django_ckeditor_5.urls")),
]

"""
Эта настройка для работы с медиа файлами только в режиме разработки проекта: если DEBUG = True.
Если DEBUG = False, то функция static() не будет работать.
static() - возвращает путь к медиа файлу, если он существует.
"""
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/models.py
from django.db import models
from django.contrib.auth.models import User  # Импортируем модель User

# Для валидации поля level
from django.core.validators import (
    MinValueValidator,
    MaxValueValidator,
)
from workplaces.models import Workplace  # Импортируем модель Workplace

# Импортируем класс поля WYSIWYG-редактора django-ckeditor-5
from django_ckeditor_5.fields import (
    CKEditor5Field,
)
from PIL import Image as PILImage  # Импортируем класс Image из библиотеки PIL

from datetime import date # Импортируем класс date для расчёта стажа

from django.core.exceptions import ValidationError # Импортируем класс ValidationError для создания валидатора

# Create your models here.


 
class Skill(models.Model):  # Класс Навык наследник базовой модели Model
    name = models.CharField(max_length=100)
    # Поле описания навыка (по желанию)
    description = CKEditor5Field(blank=True, null=True)

    # Добавляем читабельность в админке
    class Meta:
        verbose_name = "Навык"
        verbose_name_plural = "Навыки"

    def __str__(self):
        return self.name


class Employee(models.Model):  # Класс Сотрудник наследник базовой модели Model

    # Список ролей сотрудников
    ROLES = (
        ('frontend-developer','фронтенд разработчик'),
        ('backend-developer','бэкенд разработчик'), 
        ('qa-engineer', 'тестировщик'), 
        ('project-manager','руководитель проекта'), 
        ('prompt engineer', 'промпт-инженер'),
        ('other', 'другое'),
    )
    # Расширение модели User через связь с моделью User один к одному
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        verbose_name="Пользователь",
    )
    # Выбор пола
    gender = models.CharField(
        max_length=10,
        choices=(
            ("male", "Мужской"),
            ("female", "Женский"),
        ),
        verbose_name="Пол",
    )
    first_name = models.CharField(max_length=100, verbose_name="Имя")
    last_name = models.CharField(max_length=100, verbose_name="Фамилия")
    # Отчество (по желанию)
    middle_name = models.CharField(
        max_length=100, verbose_name="Отчество", blank=True, null=True
    )
    # Роль сотрудника
    role = models.CharField(choices=ROLES, verbose_name="Роль", default='other', blank=True, null=True)
    # Дата приёма на работу
    employment_date = models.DateField(verbose_name="Дата приёма на работу", blank=True, null=True)
    # Стаж в днях
    employment_days = models.PositiveIntegerField(verbose_name="Стаж в днях", blank=True, null=True, default=0, editable=False)


    # Связь с моделью Skill многие ко многим через модель SkillLevel
    skills = models.ManyToManyField(Skill, through="SkillLevel")
    # Связь с моделью Workplace один к одному.
    # Если не назначено, то в карточке сотрудника будет отображаться 'Рабочее место не назначено'
    # Удаление рабочего места не привидёт к удалению сотрудника (on_delete=models.SET_NULL)
    workplace = models.OneToOneField(
        Workplace,
        on_delete=models.SET_NULL,
        verbose_name="Рабочее место",
        blank=True,
        null=True,
    )
    # Описание сотрудника (по желанию)
    description = CKEditor5Field(blank=True, null=True)

    # Метод для расчёта стажа
    def save(self, *args, **qkwargs):   # Переопределяем метод сохранения
        if self.employment_date:        # Если дата приёма на работу заполнена
            today = date.today() # Получаем текущую дату
            days = today - self.employment_date # Рассчитываем стаж
            self.employment_days = days.days    # Записываем стаж в поле employment_days в днях
        self.full_clean()  # Проверяем валидность модели перед сохранением
        super().save(*args, **qkwargs)  # Продолжаем сохранять базовым методом модели

    # Переопределяем метод валидации
    def clean(self):
        self.validate_workplace()  # Вызываем метод валидации рабочего места

    # Метод для валидации рабочего места
    def validate_workplace(self):
        place = self.workplace.table # Получаем номер рабочего места
        neighbour_workplaces = [place - 1, place + 1] # Соседние рабочие места
        neighbours = Employee.objects.filter(workplace__table__in=neighbour_workplaces)    # Сотрудники на соседних рабочих местах
        if self.role == "qa-engineer":  # Если сотрудник тестировщик
            for neighbour in neighbours:    
                if neighbour.role == "frontend-developer":    # Если соседний сотрудник фронтенд разработчик
                    raise ValidationError(f"Сосед {neighbour} {neighbour.role} место № {neighbour.workplace} Нельзя размещать разработчиков и тестировщиков рядом")
                elif neighbour.role == "backend-developer":  # Если соседний сотрудник бэкенд разработчик
                    raise ValidationError(f"Сосед {neighbour} {neighbour.role} место № {neighbour.workplace} Нельзя размещать разработчиков и тестировщиков рядом")
        if self.role == "frontend-developer" or self.role == "backend-developer":  # Если сотрудник разработчик
            for neighbour in neighbours:    
                if neighbour.role == "qa-engineer":    # Если соседний сотрудник тестировщик
                    raise ValidationError(f"Сосед {neighbour} {neighbour.role} место № {neighbour.workplace} Нельзя размещать разработчиков и тестировщиков рядом")
                
                        

    # Добавляем читабельность в админке
    class Meta:
        verbose_name = "Сотрудник"
        verbose_name_plural = "Сотрудники"
        ordering = ['-employment_days']

    # В заголовке карточки сотрудника вместо Employee object() будет имя и фамилия
    def __str__(self):
        return f"{self.first_name} {self.last_name}"


# Связь сотрудник/навык многие ко многим через модель SkillLevel
class SkillLevel(models.Model):  # Класс Уровень Навыка наследник базовой модели Model
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    skill = models.ForeignKey(Skill, on_delete=models.CASCADE)
    level = models.IntegerField(
        default=1, validators=[MinValueValidator(1), MaxValueValidator(10)]
    )

    class Meta:  # Добавляем читабельность в админке
        verbose_name = "Уровень навыка"
        verbose_name_plural = "Уровни навыка"

    # Выводим в админке в виде: 'Сотрудник - Навык (уровень 1)'.
    # Если уровень 1, то выводим только 'Сотрудник - Навык'
    def __str__(self):
        if self.level == 1:
            return f"{self.employee} - {self.skill}"
        else:
            return f"{self.employee} - {self.skill} (уровень {self.level})"


# Создание модели для хранения изображений с отношением многие к одному (ForeignKey)
class EmployeeImage(models.Model):
    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name="employee_gallery" #
    )
    image = models.ImageField(
        upload_to="employee_images/", blank=False, null=True, verbose_name="Изображение"
    )
    is_main = models.BooleanField(default=False, verbose_name="Основное изображение")
    order = models.PositiveBigIntegerField(
        default=0, verbose_name="Порядок отображения"
    )  # Добавляем поле для сортировки изображений

    class Meta:
        ordering = ["order"]  # Сортируем изображения по порядку


    # Переопределяем метод сохранения изображения (Pillow)
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.image:
            # Проверка наличия признака основного изображения
            if self.is_main:
                # Выбираем из базы основные изображения данного сотрудника,
                # кроме нового основного, и делаем их не основными
                EmployeeImage.objects.filter(
                    employee=self.employee, is_main=True
                ).exclude(pk=self.pk).update(is_main=False)

            # Новое изображение сохраняем с изменением размера на 300х300 пикселей (метод библиотеки Pillow)
            img = PILImage.open(self.image.path)
            # max_size = (300, 300)    # Максимальные размеры изображения (реальный размер будет уменьшен до этого значения)
            img = img.resize([300, 300])  # Устанавливаем размер изображения
            # img.thumbnail(max_size, PILImage.Resampling.LANCZOS) # Сжимаем иконку изображения на странице
            img.save(self.image.path)  # Сохраняем изменённое изображение
            return self.image


    def __str__(self):
        if self.is_main:
            return f"Основное изображение для {self.employee} - {self.image.name}"
        else:
            return f"Дополнительное изображение для {self.employee}"


templates/includes/employee_card.html
<!--Код для цикла for в шаблоне staffmanager\templates\staff\employee_list.html-->    
    <b>{{ forloop.counter }}.</b>  Сотрудник: {{ employee.first_name }} {{ employee.last_name }} Стаж в Компании, дней ={{ employee.employment_days }}
    <a href="{% url 'staff:employee-detail' employee.id %}">Подробнее</a></br>   <!-- teg <a> - формат гиперссылки, указанной в атрибуте href= , 
                                                                                имя адреса гиперссылки указано в теге url и 
                                                                                задаётся в файле urls.py,
                                                                                здесь - добавить ссылку на на карточку сотрудника, 
                                                                                параметр employee.id в теге url передаём через пробел -->

    <!--Путь к фото upload_to="employee_images/" указан в image - экземпляре класса ImageField() в модели EmployeeImage-->
    <!-- выводим главное изображение в красной рамке из контекстного объекта main_image -->
    <img src="{{ employee.main_image.image.url }}" alt="PHOTO" style="border: 8px solid red;"></br></br>  

    <!--        <ul>
                 {% for image in employee.employee_gallery.all %} Перебираем все изображения в списке связанных изображений -->
    <!--                 {% if image.is_main %}                       Если это главное изображение -->
    <!--                     <img src="{{ employee.main_image.image.url }}" alt="PHOTO" style="border: 8px solid red;">    выводим главное изображение в красной рамке -->
    <!--                 {% endif %}
                {% endfor %}
            </ul>
    -->
            


templates/includes/employee_header.html
{% load static %}
{% static "css/index.css" %}        
        <header>
            <!-- Получаем данные сотрудника из встроенной модели Employee и выводим их списком -->
            СОТРУДНИК: {{ employee.first_name }} {{ employee.last_name }}</br>

            <!--Путь к фото upload_to="employee_images/" указан в image - экземпляре класса ImageField() в модели EmployeeImage-->
            <!-- выводим главное изображение в красной рамке из контекстного объекта main_image -->
            <img src="{{ main_image.image.url }}" alt="PHOTO" style="border: 8px solid red;">

            <!--<ul> 
                 {% for image in employee.employee_gallery.all %} Перебираем все изображения -->
                <!--     {% if image.is_main %}                        Если это главное изображение -->
                <!--         <img src="{{ image.image.url }}" alt="PHOTO" style="border: 8px solid red;">    выводим главное изображение в красной рамке -->
                <!--    {% endif %}
                {% endfor %}
            </ul>-->
            <ul>
                <li>user.username - {{ user.username}}</li>
                <li>employee.user_id - {{ employee.user_id }}</li>
                <li>email - {{ employee.email }}</li>
                <li>Имя - {{ employee.first_name }}</li>
                <li>Фамилия - {{ employee.last_name }}</li>
                <li>Пол - {{ employee.gender }}</li>
                <li>Дата приёма на работу - {{ employee.employment_date }}</li>
                <li>Стаж в днях - {{ employee.employment_days }}</li>
                <li>Номер стола - {{ employee.workplace }}</li>
                <li>Описание - {{ employee.description }}</li>
            </ul>
            Навыки(уровень):
            <ul>
                {% for skill_ in employee.skilllevel_set.all %}
                    <li>
                        {{ skill_.skill.name }} ({{ skill_.level }})
                    </li>
                    {% empty %}
                        <li>Нет навыков</li>
                {% endfor %}
            </ul>
            Изображения:
            <ul>
                {% for image in employee.employee_gallery.all %}
                    {% if image.image %}
                        {% if not image.is_main %}
                            <img src="{{ image.image.url }}" alt="PHOTO">
                        {% endif %}
                    {% else %}
                        <p> "нет изображения, добавьте изображение или удалите объект" </p>
                    {% endif %}
                {% endfor %}
            </ul>
        </header>

templates/includes/user_card.html
<!--Код для цикла for в шаблоне staffmanager\templates\staff\employee_list.html-->    
    <b>{{ forloop.counter0 }}. id={{user.id}}, {{ user.username }}</b>

    {{ main_image }}

    <a href="{% url 'staff:user-detail' user.id %}">Подробнее</a><br>   <!-- teg <a> - формат гиперссылки, указанной в атрибуте href= , 
                                                                                имя адреса гиперссылки указано в теге url и 
                                                                                задаётся в файле urls.py,
                                                                                здесь - добавить ссылку на страницу о книге, 
                                                                                параметр book.id в теге url передаём через пробел -->       

    {% if book.cover %}                     <!-- Проверям, есть ли обложка книги, чтобы страница "не упала", и выводим обложку -->
        <img src="{{ book.cover.url }}"/>   <!-- Путь к обложке книги указан в cover - экземпляре класса ImageField() в модели Book-->
    {% endif %}

templates/includes/user_header.html
{% load static %}
{% static "css/index.css" %}        
        <header>
            <!-- Получаем данные пользователя из встроенной модели user и выводим их списком -->
            ПОЛЬЗОВАТЕЛЬ: {{ user.username }}
            <ul>
                <li>user.username - {{ user.username}}</li>
                <li>user.password - {{ user.password }}</li>
                <li>user.email - {{ user.email }}</li>
                <li>user.first_name - {{ user.first_name }}</li>
                <li>user.last_name - {{ user.last_name }}</li>
                <li>user.groups - {{ user.groups }}</li>
                <li>user.user_permissions - {{ user.user_permissions }}</li> 
                <li>user.is_staff - {{ user.is_staff }}</li>               
                <li>user.is_superuser - {{ user.is_superuser }}</li>
                <li>user.is_active - {{ user.is_active }}</li>
                <li>user.date_joined - {{ user.date_joined }}</li>
                <li>user.last_login - {{ user.last_login }}</li>
            </ul>