staff/urls.py
from django.urls import path
from .views import (
    StaffListView,
    EmployeeDetailView,
    UserDetailView,
    UserListView,
    index,
)

app_name = "staff"  # имя приложения, которое будет использоваться в шаблонах

urlpatterns = [
    # для FBV представления
    # path('', index),                  # для FBV представления ссылка на функцю-обработчик staff/views/index.py
    # path('employee/<int:pk>/', detail),   # для FBV представления ссылка на функцю-обработчик staff/views/detail.py,
    # /<int:pk>/ - параметр пути в url для передачи в функцию-обработчик staff/views/detail.py
    # int - это конвертер типа пути, который преобразует строку в неотрицательное целое число
    
    # для CBV представления
    # используются классы EmployeeListView EmployeeDetailView в staff/views.py,
    # а в name= указывается 'user-list' 'user-detail' 'staff-list' 'employee-detail'- имена url-паттернов (в шаблонах),
    # /<int:pk>/ - параметр пути в url для встроенной функции-обработчик в классе DetailView
    # с конвертером int (строку в неотрицательное целое).
    # При необходимости изменения адреса страницы достаточно изменить адрес только в   path(''...   - имена url не меняются.

    path(
        "employee/<int:pk>/",
        EmployeeDetailView.as_view(),
        name="employee-detail",
    ),  # URL страницы с карточкой сотрудника
    path(
        "user/<int:pk>/",
        UserDetailView.as_view(),
        name="user-detail",
    ),  # URL страницы с карточкой пользователя
    path(
        "staff/",
            StaffListView.as_view(),
        name="staff-list-all",
    ),  # URL страницы со списком всех сотрудников
    path(
        "",
        #UserListView.as_view(),
        #name="user-list",
        StaffListView.as_view(),
        name="staff-last4",
    ),  # URL главной страницы со списком 4х недавно принятых сотрудников
]
   

staffmanager/urls.py
from django.contrib import admin
from django.urls import include, path

# импортируем модуль views из папки staff, содержащую функции-обработчики запросов
from staff import views

# импорт модуля debug_toolbar
import debug_toolbar

# Импорт редактора django-ckeditor-5
import django_ckeditor_5

# импорт модуля settings и функции static
# для настройки обработки медиа-файлов проекта в режиме debug
# Кроме этого, в шаблонах следует загружать тег {% load static %}
from django.conf import settings
from django.conf.urls.static import static


# Список всех адресов обработчиков запросов
urlpatterns = [
    # URL для обработчика staffmanager\staff\views.py\index()
    # path("", views.index),
    # Путь поиска ссылок в приложении staff для главной страницы
    path("", include("staff.urls")),
    # URL для обработчика из модуля admin.py
    path("admin/", admin.site.urls, name="admin"),
    # URL для обработчика из проекта DjDt
    path("__debug__/", include(debug_toolbar.urls)),
    # URL для редактора django-ckeditor-5
    path("admin/", include("django_ckeditor_5.urls")),
]

"""
Эта настройка для работы с медиа файлами только в режиме разработки проекта: если DEBUG = True.
Если DEBUG = False, то функция static() не будет работать.
static() - возвращает путь к медиа файлу, если он существует.
"""
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% load static %}
    {% static "css/index.css" %}
    <meta charset="UTF-8">  <!-- кодировка текста на странице-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Указываем блок-контент для тега <title> у наследников-->
    <title>{% block title %} Django тема 8. Итоговый проект "СОТРУДНИКИ, РАБОЧИЕ МЕСТА" {% endblock %}</title>
    <p>Header</p>
    <img src="{% static 'img\Synergy.png' %}" alt="LOGO" width="300" height="50" /> <!-- Если рисунка нет в папке - на его месте будет
                                                                                     картинка по умолчанию подписана "LOGO" -->
    <!-- подпись под рисунком-->
    <h2> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Здесь учат</h2><br>

    <a href="{% url 'staff:staff-last4' %}">На главную</a></br> <!-- teg <a> - формат гиперссылки, указанной в атрибуте href= , 
                                                                    имя адреса гиперссылки указано в теге url и 
                                                                    задаётся в файле urls.py,
                                                                    здесь - добавить ссылку на главную страницу, 
                                                                    параметр в теге url передаём через пробел -->
    <a href="{% url 'staff:staff-list-all' %}">На список сотрудников</a></br>
                                                                                                 
    <!-- устанавливаем связь шаблона index.html и таблицы стилей index.css, указывая относительный адрес url
     по отношению к __main___ с учётом того, что по умолчанию __main___
     находит шаблоны и статические файлы в директориях templates и static соответственно-->

    <link rel="stylesheet" type="text/css" href="C:\Users\EvgenyMINI_S\PythonProjects\DjangoSynergyProject\staffmanager\staffmanager\static_dev\index.css'" />
</head>
    {% block content %}
    <body>
        <main>
            Контента пока нет :() <!-- TODO: добавить контент В наследниках base.html других страниц -->
        </main>
        <footer>
            <p>Footer</p>
        </footer>
    </body>
    {% endblock %}
</html>